# Generated by Django 4.2.1 on 2023-06-20 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import e_learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_doc',
            field=models.FileField(upload_to=e_learn.models.get_file_path_assignment),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes_doc',
            field=models.FileField(upload_to=e_learn.models.get_file_path_notes),
        ),
        migrations.AlterField(
            model_name='usercourserelation',
            name='final_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserInstitutionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learn.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('CAD', 'CANADA'), ('USD', 'AMERICA')], default='CAD', max_length=3)),
                ('is_basic', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
