# Generated by Django 4.2.1 on 2023-06-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0002_assignment_content_assignment_grade_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='content',
        ),
    ]
