# Generated by Django 4.2.1 on 2023-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=models.CharField(max_length=60)),
        ),
    ]
