# Generated by Django 4.2.1 on 2023-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0005_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstitutionrelation',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinstitutionrelation',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
