# Generated by Django 4.2.1 on 2023-06-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0006_userinstitutionrelation_is_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserelation',
            name='final_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
