# Generated by Django 4.2.1 on 2023-06-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0007_alter_usercourserelation_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourserelation',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
