# Generated by Django 4.2.1 on 2023-06-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0009_assignment_content_alter_assignment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
