# Generated by Django 4.2.1 on 2023-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0011_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade_points',
            field=models.IntegerField(null=True),
        ),
    ]
