# Generated by Django 4.2.1 on 2023-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0013_alter_notes_notes_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_doc',
            field=models.FileField(upload_to='notes/None'),
        ),
    ]
