# Generated by Django 4.2.1 on 2023-06-19 16:18

from django.db import migrations, models
import e_learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0014_alter_notes_notes_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_doc',
            field=models.FileField(upload_to=e_learn.models.get_file_path),
        ),
    ]
